/**
 * Major hospitals — location SEO landing pages + internal linking hubs.
 * Clinical care is provided per physician orders; copy reflects coordination/continuity only.
 */
export const hospitals = [
  {
    slug: "ichilov-sorasky",
    shortName: "איכילוב",
    name: "המרכז הרפואי איכילוב (סוראסקי)",
    citySlug: "tel-aviv",
    region: "מרכז",
    context:
      "אחת ממחלקות המבקרים העמוסות בארץ — משפחות רבות זקוקות לליווי מוסמך בין סיבובי רופאים, ניהול תרופות וניסוח שחרור.",
  },
  {
    slug: "assuta-tel-aviv",
    shortName: "אסותא תל אביב",
    name: "בית החולים אסותא תל אביב",
    citySlug: "tel-aviv",
    region: "מרכז",
    context: "שחרורים מהירים יחסית במגוון פרוצדורות — חשוב לוודא המשכיות טיפולית בבית ובקהילה.",
  },
  {
    slug: "sheba-tel-hashomer",
    shortName: "תל השומר",
    name: "המרכז הרפואי שיבא — תל השומר",
    citySlug: "ramat-gan",
    region: "מרכז",
    context: "נפח אשפוזים גבוה ומקרים מורכבים — ליווי אחות מקצועי מסייג זמן למשפחה ותומך ביישום הוראות מדויקות.",
  },
  {
    slug: "hadassah-ein-kerem",
    shortName: "הדסה עין כרם",
    name: "הדסה עין כרם",
    citySlug: "jerusalem",
    region: "ירושלים",
    context: "משפחות מכל רחבי הארץ מגיעות לצורכי טיפול — חשובה התאמה תרבותית ולוחות זמנים גמישים לליווי.",
  },
  {
    slug: "hadassah-mt-scopus",
    shortName: "הדסה הר צופים",
    name: "הדסה הר הצופים",
    citySlug: "jerusalem",
    region: "ירושלים",
    context: "קרבה לקהילות מגוונות בעיר — דגש על תיעוד, ניהול תרופות והתאמת שפה למטופל ולמשפחה.",
  },
  {
    slug: "shaare-zedek",
    shortName: "שערי צדק",
    name: "שערי צדק",
    citySlug: "jerusalem",
    region: "ירושלים",
    context: "מחלקות רבות וזרימת שחרורים — ליווי שמקצר פערים בין מה שנאמר במחלקה לבין הבית.",
  },
  {
    slug: "bikur-cholim",
    shortName: "ביקור חולים",
    name: "ביקור חולים",
    citySlug: "jerusalem",
    region: "ירושלים",
    context: "נגישות לתושבי העיר והסביבה — שירות אחות פרטית תומך במעבר בטוח חזרה לשגרה.",
  },
  {
    slug: "rambam",
    shortName: "רמב״ם",
    name: "המרכז הרפואי רמב\"ם",
    citySlug: "haifa",
    region: "צפון",
    context: "הבי״ח המרכזי בצפון — משפחות מגיעות מחיפה, הקריות והנגב הערבות; נדרש לעיתים תיאום לוגיסטי ארוך.",
  },
  {
    slug: "bnei-zion",
    shortName: "בני ציון",
    name: "בית החולים בני ציון",
    citySlug: "haifa",
    region: "צפון",
    context: "ליווי הדוק למטופלים לאחר פרוצדורות ולצורכי קשישות בעיר ובסביבה.",
  },
  {
    slug: "carmel-haifa",
    shortName: "כרמל",
    name: "בית החולים כרמל",
    citySlug: "haifa",
    region: "צפון",
    context: "המשכיות טיפולית לתושבי חיפה והכרמל — כולל התאמה לתוואי שטח וזמני הגעה.",
  },
  {
    slug: "lin-haifa",
    shortName: "לין",
    name: "המרכז הרפואי לין",
    citySlug: "haifa",
    region: "צפון",
    context: "ליווי אשפוז ושחרור בהקשר עירוני צפוף — דגש על סדר כלים רפואיים בבית.",
  },
  {
    slug: "kaplan-rehovot",
    shortName: "קפלן",
    name: "המרכז הרפואי קפלן",
    citySlug: "rehovot",
    region: "מרכז",
    context: "מרכז רפואי אקדמי — מטופלים רבים זקוקים למעקב צפוף ימים ספורים אחרי שחרור.",
  },
  {
    slug: "bilinson",
    shortName: "בילינסון",
    name: "בית החולים בילינסון",
    citySlug: "petah-tikva",
    region: "מרכז",
    context: "נפח המון גבוה — חשוב לבנות גשר בין הוראות מחלקה לבין המשך טיפול בבית.",
  },
  {
    slug: "schneider-children",
    shortName: "שניידר",
    name: "בית החולים שניידר לרפואת ילדים",
    citySlug: "petah-tikva",
    region: "מרכז",
    context: "ליווי הורים בימים מול הילד המאושפז — הסברים, ניהול תרופות והמשכיות לשחרור.",
  },
  {
    slug: "wolfson-holon",
    shortName: "וולפסון",
    name: "בית החולים וולפסון",
    citySlug: "holon",
    region: "מרכז",
    context: "שירות למטופלים מאזור חולון, בת ים והסביבה — תיאום מהיר להמשך טיפול דומיסיליארי.",
  },
  {
    slug: "mayanei-yeshua",
    shortName: "מעייני הישועה",
    name: "בית החולים מעייני הישועה",
    citySlug: "bnei-brak",
    region: "מרכז",
    context: "רגישות תרבותית מלאה לציבור החרדי — התאמת מגדר, שעות וצורת לבוש לפי הצורך.",
  },
  {
    slug: "laniado-netanya",
    shortName: "לניאדו",
    name: "בית החולים לניאדו",
    citySlug: "netanya",
    region: "שרון",
    context: "אוכלוסייה מגוונת בעיר החוף — שפות מרובות והמשכיות לאחר שחרור.",
  },
  {
    slug: "sharon-medical",
    shortName: "השרון",
    name: "המרכז הרפואי השרון",
    citySlug: "netanya",
    region: "שרון",
    context: "מענה למטופלי השרון והסביבה — חיבור לטיפול ביתי לאחר שחרור.",
  },
  {
    slug: "meir-kfar-saba",
    shortName: "מאיר",
    name: "המרכז הרפואי מאיר",
    citySlug: "kfar-saba",
    region: "שרון",
    context: "נדבך מרכזי בשירותי השרון — ליווי קצרים וארוכים לפי צורך קליני.",
  },
  {
    slug: "lev-hasharon",
    shortName: "לב השרון",
    name: "בית החולים לב השרון",
    citySlug: "raanana",
    region: "שרון",
    context: "מטופלים מרעננה והסביבה — דגש על דיסקרטיות ושירות מקצועי.",
  },
  {
    slug: "assaf-harofeh",
    shortName: "אסף הרופא",
    name: "המרכז הרפואי אסף הרופא (שמיר)",
    citySlug: "rishon-lezion",
    region: "מרכז",
    context: "שחרורים למרכז השפלה וראשון לציון — נדרש לעיתים ליווי לילי בימים הראשונים.",
  },
  {
    slug: "assuta-rishon",
    shortName: "אסותא ראשל״צ",
    name: "בית החולים אסותא ראשון לציון",
    citySlug: "rishon-lezion",
    region: "מרכז",
    context: "תיאום עם משפחות באזור המטרופולין — שעות גמישות והמשכיות.",
  },
  {
    slug: "soroka-beer-sheva",
    shortName: "סורוקה",
    name: "המרכז הרפואי האוניברסיטאי סורוקה",
    citySlug: "beer-sheva",
    region: "דרום",
    context: "בי״ח פטרוני של הנגב — משפחות ממרחק נסיעה; ליווי מקצועי מפחית טעויות בימים הראשונים אחרי שחרור.",
  },
  {
    slug: "barzilai-ashkelon",
    shortName: "ברזילי",
    name: "בית החולים ברזילי",
    citySlug: "ashkelon",
    region: "דרום",
    context: "משרת אשקלון והסביבה — דגש על קשישים ומצבים כרוניים לאחר אשפוז.",
  },
  {
    slug: "asuta-ashdod",
    shortName: "אסותא אשדוד",
    name: "המרכז הרפואי אסותא אשדוד",
    citySlug: "ashdod",
    region: "דרום",
    context: "גידול עירוני וקהילה מגוונת — התאמת שפה ותרבות לצוות טיפול בבית.",
  },
  {
    slug: "herzliya-medical",
    shortName: "מדיקל סנטר הרצליה",
    name: "בית החולים הרצליה מדיקל סנטר",
    citySlug: "herzliya",
    region: "שרון",
    context: "משפחות הרצליה פיתוח — ציפייה לשירות מוקפד, דיסקרטיות וזמינות.",
  },
];

export const hospitalBySlug = (slug) => hospitals.find((h) => h.slug === slug);

export const hospitalsInCity = (citySlug) => hospitals.filter((h) => h.citySlug === citySlug);
